############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 3

[[main]]
name = "Social media post"
url = "#"
weight = 4
hasChildren = true

  [[main]]
  parent = "Social media post"
  name = "Instagram"
  url = "tags/"
  weight = 2
  
  
  parent = "Social media post"
  name = "YouTube"
  url = "https://www.youtube.com/channel/UCzXaGU-BmQc0AcOh_-Ijq7w"
  weight = 3
  
 [[main]]
  parent = "Social media post"
  name = "Twitter"
  url = "categories/"
  weight = 4
  
  [[main]]
  parent = "Social media post"
  name = "Linkedin"
  url = "tags/"
  weight = 5

# footer menu
[[footer]]
name = "main menu"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Feedback"
url = "contact/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4
