############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 3

[[main]]
name = "Post"
url = "#"
weight = 3
hasChildren = true

  
  parent = "Youtube"
  name = "Tags"
  url = "tags/"
  weight = 1
  
  
  parent = "Twitter"
  name = "Tags"
  url = "tags/"
  weight = 2
  
 
  parent = "Insatgram"
  name = "Categories"
  url = "categories/"
  weight = 3
  
  
  parent = "Linkedin"
  name = "Tags"
  url = "tags/"
  weight = 4

# footer menu
[[footer]]
name = "main menu"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Feedback"
url = "contact/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4
